gnupg@2.5 (new formula)
GnuPG v2.5 is the production-ready, fully-supported release that provides
post-quantum cryptography (PQC) before becoming the official v2.6-stable release:
https://lists.gnupg.org/pipermail/gnupg-announce/2025q4/000499.html

- Name is correctly declared as "GNU Privacy Guard" (not "Pretty Good Privacy")
- All compile options are enabled except for TPM and G13
- Tests use the Kyber PQC algorithms brainpoolP384r1 & ky768_bp256
- desc uses "pre 2.6-stable" indicating this is not GnuPG's "official" stable
- homepage provides the URL with complete release disambiguation info
- requires pinentry dep to ensure passphrase entry
- use --with-pinentry-pgm, --with-readline to use Homebrew deps
- use --with-pinentry-pgm to avoid conflicts with other installed agents
- use tests for pinentry/readline availability

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -18,6 +18,17 @@ jobs:
       contents: read
       pull-requests: read
     steps:
+      # This avoids conflicts and test failures with Homebrew gnupg Formulae
+      - name: Uninstall Ubuntu gnupg package
+        if: startsWith(matrix.os, 'ubuntu')
+        run: |
+          sudo apt-get remove -y "gpgconf" || true;
+          gpgconf 2>/dev/null && {
+            dpkg-query -l "gpg*" "gnupg*"
+            echo "Error: System's pre-installed gpg still exists" >&2
+            exit 1
+          } || true
+
       - name: Set up Homebrew
         id: set-up-homebrew
         uses: Homebrew/actions/setup-homebrew@main
